language: c
os: linux

env:
  global:
    # Set "false" to force rebuild of third-party dependencies.
    - CACHE_ENABLE=true

jobs:
  include:
    - stage: baseline
      os: linux
      compiler: gcc

#    - stage: sanitizers
#      os: linux
#      compiler: clang-6.0

#TODO
#documentation
#unit-tests
#metrics
#lint
#cpp.py

#TODO clean those stages:
#before_install: ci/before_install.sh
#install:        ci/install.sh
#before_script:  ci/before_script.sh
#script:         ci/script.sh
#before_cache:   ci/before_cache.sh

addons:
  apt:
    packages:
      - clang-6.0
      - cmake
      - gcc-multilib
      - valgrind
